// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYp1uaDjsYJwg-Rh8eOlnA00cNupCKD8',
    appId: '1:469273859035:web:d37c8a4df35e5a47638dfe',
    messagingSenderId: '469273859035',
    projectId: 'spendly-expense-tracker-8a3d4',
    authDomain: 'spendly-expense-tracker-8a3d4.firebaseapp.com',
    storageBucket: 'spendly-expense-tracker-8a3d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsrR96xxg152257G1X-qkwA1B99fZbI1s',
    appId: '1:469273859035:android:51b00354d340f917638dfe',
    messagingSenderId: '469273859035',
    projectId: 'spendly-expense-tracker-8a3d4',
    storageBucket: 'spendly-expense-tracker-8a3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvaXpyIRrnt8HSIuOxBYr-2XobGAKUgqw',
    appId: '1:469273859035:ios:566485a5267d3ba4638dfe',
    messagingSenderId: '469273859035',
    projectId: 'spendly-expense-tracker-8a3d4',
    storageBucket: 'spendly-expense-tracker-8a3d4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvaXpyIRrnt8HSIuOxBYr-2XobGAKUgqw',
    appId: '1:469273859035:ios:566485a5267d3ba4638dfe',
    messagingSenderId: '469273859035',
    projectId: 'spendly-expense-tracker-8a3d4',
    storageBucket: 'spendly-expense-tracker-8a3d4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLYp1uaDjsYJwg-Rh8eOlnA00cNupCKD8',
    appId: '1:469273859035:web:49e5f68ac4f3bdcb638dfe',
    messagingSenderId: '469273859035',
    projectId: 'spendly-expense-tracker-8a3d4',
    authDomain: 'spendly-expense-tracker-8a3d4.firebaseapp.com',
    storageBucket: 'spendly-expense-tracker-8a3d4.firebasestorage.app',
  );
}
